name: Compile

on:
    push:
        branches: ["main", "master"]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: ["main", "master"]

jobs:
    eslint:
        name: Test code compilation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm install

            - name: Check Formatting
              run: npx prettier --check .

            - name: Compile Code
              run: npm run compile
